### ISSUE TITLE
Error when loading Driver.py

### ISSUE THREAD

**Issue by VictoryFirst1** [AndrejGobeX/TrackMania_AI#10]
I followed the instructions, but when I have found Driver.py and enter python Driver.py Neptune, I get this error message:
![image](https://user-images.githubusercontent.com/101500879/158133833-936d71a4-80a3-4d4d-ba8b-7e59c4397f5c.png)
Did I do everything correctly?

**Comment by VictoryFirst1** [comment]
![image](https://user-images.githubusercontent.com/101500879/158134067-93dd23c5-b599-4e18-bfbc-9c13ff4c1d95.png)
That was the wrong picture lol

**Comment by AndrejGobeX** [comment]
you need to install the required packages using pip
