### ISSUE TITLE
Cannot find Python

### ISSUE THREAD

**Issue by VictoryFirst1** [AndrejGobeX/TrackMania_AI#11]
Almost there, I installed PIL package, but now I get this error:

![image](https://user-images.githubusercontent.com/101500879/158160013-79d723b9-c36a-42ba-b520-bc5fb9efc542.png)

Translation:
Python was not found. Run without arguments to install from Microsoft Store or disable this shortcut in Settings > Manage App Run Aliases.

![image](https://user-images.githubusercontent.com/101500879/158160410-62bb87a4-ad7d-4cc6-92b4-d7cf02cb0d21.png)
The two with python in the name were enabled. I disabled both, and then the error message changed to 'python' is not recognized as a command. I enabled only last one, same issue. I enabled only the first one, the error "Python not found" appeared again.

**Comment by AndrejGobeX** [comment]
i don't know, maybe it's because you are running from one drive.
that is not related to my project, i would advise googling a bit
