### ISSUE TITLE
Another issue...

### ISSUE THREAD

**Issue by ZeraBlayde** [AndrejGobeX/TrackMania_AI#12]
Took a bit of a break and came back and did all of your and others' recommendations. It's further than i've gotten before, but i'm a bit stuck. again, sorry if this is simple and i'm just stupid. ![Screenshot 2022-03-17 161857](https://user-images.githubusercontent.com/96992892/158896895-fd5f8872-d72b-427e-8647-3f8dacdece07.png) Thanks,
-zera

**Comment by AndrejGobeX** [comment]
you need to install required packages

pip install pillow ...
explore python in general it will be much easier for you
