### ISSUE TITLE
Run RL_Driver.py to error

### ISSUE THREAD

**Issue by 129beer** [AndrejGobeX/TrackMania_AI#15]
D:\AIgame\TrackMania_AI-main_new>python RL_Driver.py
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "D:\AIgame\TrackMania_AI-main_new\RL_Driver.py", line 30, in <module>
    obs, _ = env.reset()
  File "D:\AIgame\TrackMania_AI-main_new\TrackmaniaEnv.py", line 325, in reset
    self.respawn()
  File "D:\AIgame\TrackMania_AI-main_new\TrackmaniaEnv.py", line 154, in respawn
    self.refresh_observation()
  File "D:\AIgame\TrackMania_AI-main_new\TrackmaniaEnv.py", line 172, in refresh_observation
    view = self.visualizer.lidar(self.location, TrackmaniaEnv.vector_angle(self.direction), show=False)
  File "D:\AIgame\TrackMania_AI-main_new\TrackVisualizer.py", line 113, in lidar
    return self.lidar_13(img, show=show) / TrackVisualizer.MAX_DISTANCE
  File "D:\AIgame\TrackMania_AI-main_new\TrackVisualizer.py", line 89, in lidar_13
    index = armin(np.all(img[axis_x, axis_y] < self.black_threshold, axis=1))
IndexError: index 100 is out of bounds for axis 0 with size 88

**Comment by AndrejGobeX** [comment]
Which map?

**Comment by 129beer** [comment]
sorry this new error.when i run the  RL_Driver.py about 10s . print a new error
D:\AIgame\TrackMania_AI-main_new>python RL_Driver.py
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Action timeout:  0.5159430027008056
None
None
None
None
None
Observation timeout:  3.170051574707044e-05
None
None
None
None
None

D:\AIgame\TrackMania_AI-main_new>.
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\AIgame\TrackMania_AI-main_new>..
'..' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\AIgame\TrackMania_AI-main_new>..
'..' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\AIgame\TrackMania_AI-main_new>..
'..' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\AIgame\TrackMania_AI-main_new>..
'..' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\AIgame\TrackMania_AI-main_new>..
'..' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\AIgame\TrackMania_AI-main_new>..
'..' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\AIgame\TrackMania_AI-main_new>..
'..' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\AIgame\TrackMania_AI-main_new>..
'..' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\AIgame\TrackMania_AI-main_new>..
'..' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by AndrejGobeX** [comment]
I don't understand, can you describe the issue?

**Comment by 129beer** [comment]
Sorry, it's my fault.
'''
The first error is reported IndexError: index 100 is out of bounds for axis 0 with size 88
'''
Is it because I didn't select the correct map
The following error
'''
D:\AIgame\TrackMania_AI-main_new>..
'..' is not recognized as an internal or external command, operable program
or a batch file.

D:\AIgame\TrackMania_AI-main_new>..
'..' is not recognized as an internal or external command, operable program
or a batch file.
'''
It seems that my mouse is not clicking into the game interface
It's working fine now

**Comment by AndrejGobeX** [comment]
Yep, you need to alt+tab to the game after running the script. Glad it works now!
