### ISSUE TITLE
Index out of Range

### ISSUE THREAD

**Issue by TheUntitledGoose** [AndrejGobeX/TrackMania_AI#17]
This time, unlike my previous pull request, I'm not a dumbass. Actual issue.

When ran with a .Challenge.Gbx file it returns an error:
`System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'`

**Comment by AndrejGobeX** [comment]
For the c#?

**Comment by TheUntitledGoose** [comment]
Yeah, after compilation and running it on the Fall 2023 campaign first map.

**Comment by AndrejGobeX** [comment]
It only works for flat custom maps
