### ISSUE TITLE
Trying to learn

### ISSUE THREAD

**Issue by jondeyoung** [AndrejGobeX/TrackMania_AI#18]
I did my best to follow the directions, but I keep getting the following error: ModuleNotFoundError: No module named 'gymnasium'.  Any ideas on what I did wrong?

**Comment by AndrejGobeX** [comment]
When you install stablebaselines make sure to add the version:

`pip install stable-baselines3==2.0.0`

This should pull the gymnasium as well.
Let me know if that worked.
