### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by NumseBacon** [AndrejGobeX/TrackMania_AI#3]
Yo can I contact you on discord

**Comment by AndrejGobeX** [comment]
Sure, how can i send you a dm here :) ?
Or better ask here so others can see, it might be of use of other people

**Comment by NumseBacon** [comment]
I have no idea how to dm o.o

**Comment by AndrejGobeX** [comment]
Post it here

**Comment by NumseBacon** [comment]
Well I just need help with tensorflow lol :p

**Comment by AndrejGobeX** [comment]
Yeah, I really should put Setup section in readme
What is the issue?

**Comment by NumseBacon** [comment]
https://gyazo.com/24f5c476f3ea4746f3d0b781c56a9915 this :/

**Comment by AndrejGobeX** [comment]
I do not intend to open random links, sry
Could you say what seems to be the problem

**Comment by NumseBacon** [comment]
![billede](https://user-images.githubusercontent.com/49767592/129458926-a257481e-495f-4359-ba26-9702109d856f.png)

**Comment by AndrejGobeX** [comment]
Hmm, haven't had such problem, r u on windows?

**Comment by NumseBacon** [comment]
Yup

**Comment by AndrejGobeX** [comment]
I can only think of a dependency missmatch.
Either try to find on stackoverflow
or
try to create a new virtual env for python (or just remove it and reinstall), then just install tensorflow
I know it's not the answer you were looking for but i really don't know
Python 3.9? Maybe try 3.7 or 8

**Comment by NumseBacon** [comment]
What is your tensorflow version?

**Comment by AndrejGobeX** [comment]
Don't remember, removed it recently

**Comment by NumseBacon** [comment]
Dang. Ive already tried all of those things multiple times :/

**Comment by AndrejGobeX** [comment]
Tensorflow has dependencies
Install only tensorflow with python 3.7 or 8
If that doesn't work, try to install a previous version of tf
I haven't used cuda etc

**Comment by NumseBacon** [comment]
could it be because im using tf v2?

**Comment by AndrejGobeX** [comment]
No, i used v2

**Comment by NumseBacon** [comment]
I just installed a new version of tenserflow (2.2.0) and it installed the dependencies but still shows that error

**Comment by AndrejGobeX** [comment]
Try an older version, or older python, or research the error

**Comment by NumseBacon** [comment]
Yea ive searched a lot and havent found anything

**Comment by NumseBacon** [comment]
Just tried the nightly build, that not doesnt work either

**Comment by NumseBacon** [comment]
@AndrejGobeX good news rn, now it says it needs the module "mods", what module is that?

**Comment by NumseBacon** [comment]
Ok so, I managed to do everything but I don't know what to do lol I ran trainer.py but idk

**Comment by NumseBacon** [comment]
![billede](https://user-images.githubusercontent.com/49767592/129488373-59e330b9-dec9-4607-9e35-20fbf7855b65.png)
 now this?

**Comment by NumseBacon** [comment]
Im trying to run the screenrecorder but when I do it saus not enough arguments. I figured out what PID was but I have no idea what speed address and endian is :/

**Comment by AndrejGobeX** [comment]
I will try to add everything in readme
For now, speed address is the memory address of the speed variable in trackmania (you use CheatEngine)
PID is the ID of the trackmania (open task manager and find the PID)
when running scripts, at the top of the script is usually a comment telling you how to run a script
You can explore them for yourself
Screenrecorder is used to take snapshots while you play the game. These are used to train the nets
For now, try driver.py
Run it like:
python driver.py net pid speedaddress (net should be either Neptune or Maniack) there is an example in the script
run trackmania and then run the script, once you see ready or press s to start, alt tab to trackmania (you should already be in the driver mode), press delete to respawn and hit s to start the ai
endian dont worry it all set up

**Comment by NumseBacon** [comment]
How do I find the speed variable in TM? Under memory view or?

**Comment by AndrejGobeX** [comment]
CheatEngine
Run it, select trackmania, and find the value
There is a simple tutorial for it

**Comment by NumseBacon** [comment]
well im pausing the game and putting the speed value into the cheat engine search and doing it multiple times, but I end up with values that stop working after ive completed a track

**Comment by AndrejGobeX** [comment]
yeah thats a problem
i know, when I use this, I usually respawn before the end
When u finish everything resets

**Comment by NumseBacon** [comment]
just to be sure, what value type?

**Comment by AndrejGobeX** [comment]
default, im not sure what u mean

**Comment by NumseBacon** [comment]
In cheat engine

**Comment by AndrejGobeX** [comment]
just leave default

**Comment by NumseBacon** [comment]
![billede](https://user-images.githubusercontent.com/49767592/129490287-7e572abb-44a3-4cd3-afe5-3003775f8774.png)
none of these are working

**Comment by NumseBacon** [comment]
as in it gives me not enough arguments in cmd

**Comment by AndrejGobeX** [comment]
depends on the script
open driver, look at the top there is an example
fill in all the stuff (place the AF19C... for speed)
should run

**Comment by NumseBacon** [comment]
![billede](https://user-images.githubusercontent.com/49767592/129490366-fe032067-8b8a-4d33-aed6-66d7a4f6e7cb.png)
yea this and still not enough arguments

**Comment by AndrejGobeX** [comment]
call python
python Driver....

**Comment by NumseBacon** [comment]
thats stupid

**Comment by AndrejGobeX** [comment]
it works?

**Comment by NumseBacon** [comment]
Well yea. I wait for it to say ready, and then I click s and it waits like 20 sec before anything happens and then I try to click q and it doesnt stop

**Comment by AndrejGobeX** [comment]
hmmm, i dont now the specs of your pc, but i can tell you that you can tap q multiple times
or just alt tab to cmd and ctrl+c couple of times (not the best solution, but it aint the point of the project)
as for the delay, dont really know, press s few times or hold it longer

**Comment by NumseBacon** [comment]
Ok so! Its driving kinda. When the count down reaches 0 it takes a few seconds for it to drive, SO now do I kinda train it do become faster

**Comment by AndrejGobeX** [comment]
now u can do whatever you want, explore the repo and enjoy

**Comment by NumseBacon** [comment]
But how do I train it to become better

**Comment by AndrejGobeX** [comment]
trainer + screenrecorder
explore the repo on your own, its easy to understand

**Comment by NumseBacon** [comment]
So just drive a lot with screenrecorder and then trainer.py?

**Comment by AndrejGobeX** [comment]
yep, but machine learning is much more than that
just research play etc

**Comment by NumseBacon** [comment]
idk what you mean by research play

**Comment by NumseBacon** [comment]
You also said "I plan to do reinforcement/evolution/mutation net in the future" when u gonna do that?

**Comment by AndrejGobeX** [comment]
So I tried it with the latest versions of everything and it worked well, I fixed a small issue considering speedcapture
It sould work fine now
As for RL, I'm working on it
