### ISSUE TITLE
Unable to load plugin properly

### ISSUE THREAD

**Issue by nmcgee-msft** [AndrejGobeX/TrackMania_AI#5]
Hi,

Thanks for sharing this work.  When I load the plugin for OpenPlanet, it gives this message in the log and never creates the listener:

![image](https://user-images.githubusercontent.com/27708966/143327012-312094c4-8846-4315-ba22-c5cfdaf58cdf.png)

Is the signature a concern, or normal?  I've tried opening as much as possible on my firewall to allow it to create the server, but so far nothing is showing up as listening on port 9000 as specified in the script.  Any ideas are appreciated.  Thanks!

**Comment by nmcgee-msft** [comment]
I found the issue.  Apparently this plugin doesn't work on starter level.  I upgraded to the Club version and the plugin loaded immediately.

![image](https://user-images.githubusercontent.com/27708966/143346277-9cede27b-cab7-473d-836b-fc518eb2f1ba.png)

**Comment by AndrejGobeX** [comment]
No no, I use starter access and it works fine. I wonder how it works? Don't waste your money for nothing :)

**Comment by nmcgee-msft** [comment]
Oops, too late :).  I read on OpenPlanet's site that some plugins will not work without proper signatures, but the paid versions lifted those restrictions.  For whatever reason, the plugin loaded right away after upgrading but the synthesized keystrokes did not make it to the app until I ran trackmania.exe directly versus using the Epic Games launcher.  Perhaps launching this way would have also been the key to avoiding the signature error.

Thanks for confirming that it should have worked without upgrading.  If I am still tinkering with anything related to this in a year's time I will know that I don't need to redo the subscription.

**Comment by AndrejGobeX** [comment]
I am glad you tried the project! If you have any questions ask. You might clear the subscription if tm has a 7day trial or smth i dont know.

**Comment by AndrejGobeX** [comment]
Wow you might be right, I always ran it by .exe (I am using ubisoft connect, not epic games). Anyway, thanks for the heads up!
