### ISSUE TITLE
Driver.py giving a "ready" but then also giving out an error message

### ISSUE THREAD

**Issue by Kanenashi** [AndrejGobeX/TrackMania_AI#6]
File "D:\Python399\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "D:\Python399\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "D:\TrackMania_AI-main\Driver.py", line 61, in data_getter_function
    s.connect(("127.0.0.1", 9000))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by AndrejGobeX** [comment]
I don't know, perhaps the port is already in use. However, you cannot change it as it is in the plugin. First fire up the game, see Waiting for connection in openplanet log, then use Driver.py. You can try to create a single socket in a different script, just to see what's the problem. I can tell you the usual (restart the computer, follow the setup) but I believe you have already tried that. Also, try installing python in C:, I had issues with D: for different programs.

**Comment by Kanenashi** [comment]
Ok I'll check again since my C drive only has 200 MB left

**Comment by Kanenashi** [comment]
I didn't check the logs and I got an invalid signature error for the plugin

**Comment by AndrejGobeX** [comment]
Ok, so that happens if you are on EpicGames launcher. Try running the game from .exe, or use UbisoftConnect

**Comment by Kanenashi** [comment]
I used ubisoft connect and I got the same error still

**Comment by AndrejGobeX** [comment]
Did you clone this repo? It can sometimes download a scrambled file. You need to copy both plugin and signature files to the openplanet folder.

**Comment by Kanenashi** [comment]
I'm sorry but uh... I downloaded.

**Comment by Kanenashi** [comment]
and yes I have copied both files

**Comment by AndrejGobeX** [comment]
Ok, so download git for windows. Then, git clone this repo, and then copy the files

**Comment by Kanenashi** [comment]
.as and .sig right?

**Comment by AndrejGobeX** [comment]
yes

**Comment by Kanenashi** [comment]
Both files are in scripts folder for openplanet

**Comment by Kanenashi** [comment]
I copied both of them as you said in the instructions

**Comment by AndrejGobeX** [comment]
I don't know exactly. All I can do is tell you to try various things. Every issue that is solved, I put in the readme. I haven't seen this yet. Usually the solution is to use git to clone the repo and Ubisoft Connect. You can also try to hash the files so I can check if they aren't scrambled

**Comment by Kanenashi** [comment]
How do I hash the files? I'm new to github

**Comment by AndrejGobeX** [comment]
google certutil, open cmd

certutil -hashfile "plugin file" SHA1
certutil -hashfile "sig file" SHA1

save the hashes

**Comment by Kanenashi** [comment]
6f64dd63d8a9ee776c92d09be773b07a85a25996 for the .as
2cbc5d2206ca5c3e7483435d3b9da38b0bc966b7 for the as.sig

**Comment by Kanenashi** [comment]
that's it right?

**Comment by AndrejGobeX** [comment]
as.sig is ok, the .as is not
it is 2e627700f726f9883781d61f238024c61a2f745a

don't edit that file

**Comment by Kanenashi** [comment]
so do I download it again?

**Comment by Kanenashi** [comment]
git clone it then

**Comment by AndrejGobeX** [comment]
Don't know, try to download it again, maybe you don't need to git clone but it will work definitely

**Comment by Kanenashi** [comment]
Ok on it

**Comment by Kanenashi** [comment]
I downloaded it again and I still got the same error of invalid signature

**Comment by AndrejGobeX** [comment]
Is the hash ok?

**Comment by Kanenashi** [comment]
I got the same hash
6f64dd63d8a9ee776c92d09be773b07a85a25996

**Comment by AndrejGobeX** [comment]
No, that means that the file is not ok. You need to have a file that produces the hash i gave you

**Comment by Kanenashi** [comment]
so gitclone it then?

**Comment by AndrejGobeX** [comment]
It will work.

**Comment by Kanenashi** [comment]
Ok I'm git cloning and it worked
the hash matches

**Comment by Kanenashi** [comment]
But I still get an invalid signature and it says "Loading legacy plugin"

**Comment by AndrejGobeX** [comment]
I really don't know, try reinstalling the game or running from .exe or check if you copied files correctly. If you find a solution, let me know so I can write it in the readme for others

**Comment by Kanenashi** [comment]
I recopied the files again
and now I get this error
File "D:\Python399\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "D:\Python399\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "D:\TrackMania_AI-main\Driver.py", line 63, in data_getter_function
    data = GetData.get_data(s)
  File "D:\TrackMania_AI-main\GetData.py", line 7, in get_data
    data['speed'] = unpack(b'@f', s.recv(4))[0] * 3.6 # speed
struct.error: unpack requires a buffer of 4 bytes

**Comment by AndrejGobeX** [comment]
The plugin works?
If the plugin works I do not know why this won't work

**Comment by Kanenashi** [comment]
#0 Void main() D:/TrackmaniaNext/Openplanet/Scripts/Plugin_GrabData_0_1.as as line 46
That's the error message I get when I use driver.py in the Logs

**Comment by Kanenashi** [comment]
sorry for being such an idiot

**Comment by AndrejGobeX** [comment]
Wait, how? That's from plugin, they are not connected directly

**Comment by AndrejGobeX** [comment]
I really recommend to place everything on C:
