### ISSUE TITLE
Import Error when inputting `python Driver.py Neptune`

### ISSUE THREAD

**Issue by ZeraBlayde** [AndrejGobeX/TrackMania_AI#7]
Title, A screenshot for reference

![Screenshot 2022-01-02 154115](https://user-images.githubusercontent.com/96992892/147890257-9bd0ac2d-50ac-4472-a817-53b032d9d44a.png)

**Comment by ZeraBlayde** [comment]
Also I'm pretty new to python so if this is obvious sorry for being an inconvenience

**Comment by AndrejGobeX** [comment]
I don't know, but I can see that you have installed python in Desktop/, not in default location. Also, I don't know from where you are importing basic modules. You are using python 3.7, but the traceback.py and linecache.py are from 3.9. I would recommend you to remove older versions and keep 3.9 or remove them all and install 3.9 (use the default settings + PATH checkbox). Do not edit the scripts if you are unsure.

**Comment by ZeraBlayde** [comment]
alright, thanks. i was using 3.7 for rlbot but i'm done with that so i'll try it.

**Comment by asdat3** [comment]
he was not running in the right directory thats it

the file (driver.py) couldnt import the other files as they where not in the same location as the execution

simply fix this by cd into the directory of this repository.
And learn how to manage your folders
