### ISSUE TITLE
Unable to load plugin 

### ISSUE THREAD

**Issue by VictoryFirst1** [AndrejGobeX/TrackMania_AI#9]
I have Ubisoft Connect, I run the game directly via .exe, I did exactly what is stated in the setup, but every time I get this error message:
![image](https://user-images.githubusercontent.com/101500879/158053550-1efe0481-9809-4207-8653-91136a312572.png)

**Comment by AndrejGobeX** [comment]
This was already answered in the issues,
you need to clone the repo with git.
Check the hashes of the script and the signature file. If they do not match, you need to download again.
